import scipy.io
import numpy as np
import matplotlib.pyplot as plt
import os

def plot_convergence(mat_filepath, save_path="convergence_plot.pdf"):
    """
    Loads error data from a .mat file and generates a publication-ready log-log plot.
    """
    if not os.path.exists(mat_filepath):
        raise FileNotFoundError(f"Data file not found: {mat_filepath}")

    # 1. Configure Matplotlib for Publication Quality
    plt.rcParams.update({
        "font.family": "Times New Roman",
        "font.serif": ["Times New Roman", "Computer Modern Roman", "DejaVu Serif"],
        "font.size": 12,
        "axes.labelsize": 14,
        "axes.titlesize": 14,
        "legend.fontsize": 11,
        "xtick.labelsize": 11,
        "ytick.labelsize": 11,
        "lines.linewidth": 2,
        "lines.markersize": 8,
        "figure.autolayout": True
    })

    # 2. Load the Data
    data = scipy.io.loadmat(mat_filepath)
    errors = data['errors']
    N_s = data['N_s'].flatten()

    
    # EPS values as defined in your convergence_analysis function
    EPS = [0.0001]
    
    # 3. Initialize Figure
    fig, ax = plt.subplots(figsize=(7, 5))
    
    # Styling for lines
    markers = ['o', 's', '^', 'D']
    colors = ['#1f77b4', '#ff7f0e', '#2ca02c', '#d62728'] # Distinct, colorblind-friendly
    
    # 4. Plot each error line
    for i, eps in enumerate(EPS):
        if eps != 1:
            if i < errors.shape[0]: # Ensure we only plot data that was actually saved
                ax.loglog(N_s, errors[i, :], 
                        marker=markers[i % len(markers)], 
                        color=colors[i % len(colors)], 
                        label=rf'$\epsilon = {eps}$')

    # 5. Add a reference slope (Optional but recommended for publications)
    # Assuming first-order convergence O(1/N) for implicit heat integration.
    # We anchor it to the first point of the last plotted curve for clean visualization.
    if errors.shape[0] > 0 and len(N_s) >= 2:
        ref_N = N_s # Take the last 3 N values for the reference line
        ref_err = 1/(ref_N)  # 1st-order slope
        
        ax.loglog(ref_N, ref_err*0.25, color='black', linestyle='--', label=r'$\mathcal{O}(N^{-1})$')

    # 6. Formatting the Axes
    ax.set_xlabel('Number of Time Steps ($N$)')
    ax.set_ylabel('$L_2$ Error')
    ax.set_title('Convergence Analysis')
    
    # Clean grid lines
    ax.grid(True, which="major", linestyle="-", alpha=0.6)
    ax.grid(True, which="minor", linestyle=":", alpha=0.4)
    
    # Legend formatting
    ax.legend(frameon=True, edgecolor='black', loc='best')
    ax.set_ylim(1e-6, 5*1e-1)
    
    # 7. Save and Display
    plt.savefig(save_path, dpi=300, bbox_inches='tight')
    print(f"Plot successfully saved to {save_path}")
    plt.show()

if __name__ == "__main__":
    # Note: You will need to adjust this filename based on the actual output 
    # generated by your script (e.g., domain_type, alpha, lambda_damp, etc.)
    
    # Example matching the parameters in your main block: 
    # alpha=0.5, domain_type="L", lambda_damp=0.0
    file_path = "error_mats/errors_heat_lambda0.0_inicond_hs6_3e-5_alpha0.1_L_simpson_10_N_4-15_Eps_0.1-0.01-0.001-0.0001.mat"
    
    try:
        plot_convergence(file_path, save_path="heat_eq_convergence_L.pdf")
    except FileNotFoundError as e:
        print(e)
        print("Please verify the filename matches the exact string generated by your scipy.io.savemat call.")